# Generated by Django 3.0.2 on 2020-01-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=15)),
                ('Maritalstatus', models.TextField()),
                ('Block', models.CharField(max_length=10)),
            ],
        ),
    ]
